const SET_CART_LIST = 'SET_CART_LIST'
const UPDATE_ISCHOOSED = 'UPDATE_ISCHOOSED'
const SET_PROMOTIONS ='SET_PROMOTIONS'
const UPDATE_CART_CODE_LIST = 'UPDATE_CART_CODE_LIST'

export {
    SET_CART_LIST,
    UPDATE_ISCHOOSED,
    SET_PROMOTIONS,
    UPDATE_CART_CODE_LIST
}