import { syncCart } from "../actionCreate/cart"

const UPDATE_ISCHOOSED = 'UPDATE_ISCHOOSED'
const SET_PROMOTIONS ='SET_PROMOTIONS'
const CECHK_ALL_CART_ITEMS = 'CHECK_ALL_CART_ITEMS'

const UPDATE_ITEM_COUNT = 'UPDATE_ITEM_COUNT'

const SET_RENDER_CART = 'SET_RENDER_CART'
const SYNC_CART_ITEMS = 'SYNC_CART_ITEMS'

const SET_CART = 'SET_CART'
const FLAG_DEL = 'FLAG_DEL'
const DEL_ITEMS = 'DEL_ITEMS'


const CHANGE_PAYMENT = "CHANGE_PAYMENT"

export {
    UPDATE_ISCHOOSED,
    SET_PROMOTIONS,
    CECHK_ALL_CART_ITEMS,
    UPDATE_ITEM_COUNT,
    SET_RENDER_CART,
    SYNC_CART_ITEMS,
    SET_CART,
    DEL_ITEMS,
    FLAG_DEL,
    CHANGE_PAYMENT

}