const SET_ALL_DATA = 'SET_ALL_DATA'
const SET_PREVIEW_DATA = 'SET_PREVIEW_DATA'
const SET_URL_PRO = 'SET_URL_PRO'
const SET_ACTIVE = 'SET_ACTIVE'
const SET_PRO_NUM = 'SET_PRO_NUM'
const SET_TYPE_ARR = 'SET_TYPE_ARR'
const SET_INDEX = 'SET_INDEX'
const CLEAR_DATA = 'CLEAR_DATA'
export {
    // GET_DATA_DETAIL,
    // GET_DATA_BANNER,
    SET_ALL_DATA,
    SET_PREVIEW_DATA,
    SET_URL_PRO,
    SET_ACTIVE,
    SET_PRO_NUM,
    SET_TYPE_ARR,
    SET_INDEX,
    CLEAR_DATA
}
